In [1]:
import math
import numpy as np

def numpy_fillna(data):
    # Get lengths of each row of data
    lens = np.array([len(i) for i in data])

    # Mask of valid places in each row
    mask = np.arange(lens.max()) < lens[:,None]

    # Setup output array and put elements from data into masked positions
    out = np.full(mask.shape, np.nan, dtype=data.dtype)
    out[mask] = np.concatenate(data)
    return out


In [3]:
def PasteUnfitArray(MasterArray,InsertedArray):
    print(np.shape(MasterArray))
    print(np.shape(InsertedArray))
    

print(np.arange(len([1,2,3,4,5])))


Results = np.array([0,0])
Results = np.append(Results,5)
nbofBins = math.floor(14/15)
remainder = 14%15
print(nbofBins,remainder)
print(np.size(Results,0))
if np.size(Results,0) == 0 :
    print("chier")
print(Results)
Results = np.append(Results,np.array([[5]]))
print(Results)
Results = np.append(Results,np.array([[5]]))
print(Results)
Results = np.append(Results,np.array([[np.nan]]))
print(Results)


data = np.array([[1, 2, 3, 4],
                 [2, 3, 1],
                 [5, 5, 5, 5],
                 [1, 1]],dtype=object)
print(data)
objecti=np.array([[12,15,4,45,7]],dtype=object)

PasteUnfitArray(data,objecti)



#data = np.append(data,objecti)

#print(data)
#print(np.shape(data))
#newdata = numpy_fillna(data)
#print(newdata)
#print(np.shape(newdata)#)

[0 1 2 3 4]
0 14
3
[0 0 5]
[0 0 5 5]
[0 0 5 5 5]
[ 0.  0.  5.  5.  5. nan]
[list([1, 2, 3, 4]) list([2, 3, 1]) list([5, 5, 5, 5]) list([1, 1])]
(4,)
(1, 5)
